# **Data Cleaning**

## **NDTV**

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('/content/en_top3_insights_NDTV.csv')
df.head(5)

FileNotFoundError: [Errno 2] No such file or directory: '/content/en_top3_insights_NDTV.csv'

In [ ]:
df.isna().sum()

url                      0
title                    0
publish_date             0
authors                  0
length                   0
likes                    0
comments                 0
views                    0
description              0
political                0
non political            0
topic                    0
cleaned_description      0
text                     0
cluster                  0
score                    0
video_id                 0
captions                45
Caption Summary          0
Orientation            216
Explanation              0
Target Party           223
Target Person          196
Sentiment                7
dtype: int64

In [ ]:
df['Target Party'].unique()

array(['BJP(Bharatiya Janta Party)', 'TMC(Trinamool Congress)', nan,
       'BJP', 'INC(Indian National Congress)', 'BJP and INC',
       'BJD (Biju Janata Dal)', 'INDIA bloc (which includes INC and AAP)',
       'RJD (Rashtriya Janata Dal)', 'BRS (Bharat Rashtra Samithi)',
       'BRS', 'AAP and INC',
       'INC(Indian National Congress) and AAP(Aam Aadmi Party)',
       'JMM (Jharkhand Mukti Morcha)', 'AAP', 'AAP(Aam Aadmi Party)',
       'YSR Congress Party (YSRCP)', 'BJD', 'TDP (Telugu Desam Party)',
       'YSRCP', 'Congress', 'JDS (Janata Dal Secular)',
       'YSR Congress Party', 'Conservative Party',
       'TMC (Trinamool Congress)', 'Trinamool Congress', 'AIMIM'],
      dtype=object)

In [ ]:
df['Target Party'].isna().sum()

223

In [ ]:
df['Target Party'] = df['Target Party'].replace('BJP(Bharatiya Janta Party)', 'BJP')
df['Target Party'] = df['Target Party'].replace('INC(Indian National Congress)', 'INC')
df['Target Party'] = df['Target Party'].replace('INDIA bloc (which includes INC and AAP)', 'INC')
df['Target Party'] = df['Target Party'].replace('Congress', 'INC')
df['Target Party'] = df['Target Party'].replace('Trinamool Congress', 'TMC')
df['Target Party'] = df['Target Party'].replace('AAP(Aam Aadmi Party)', 'AAP')
df['Target Party'] = df['Target Party'].replace('TMC(Trinamool Congress)', 'TMC')
df['Target Party'] = df['Target Party'].replace('TMC (Trinamool Congress)', 'TMC')
df['Target Party'] = df['Target Party'].replace('BRS (Bharat Rashtra Samithi)', 'BRS')
df['Target Party'] = df['Target Party'].replace('RJD (Rashtriya Janata Dal)', 'RJD')

In [ ]:
df['Target Party'].unique()

array(['BJP', 'TMC', nan, 'INC', 'BJP and INC', 'BJD (Biju Janata Dal)',
       'RJD', 'BRS', 'AAP and INC',
       'INC(Indian National Congress) and AAP(Aam Aadmi Party)',
       'JMM (Jharkhand Mukti Morcha)', 'AAP',
       'YSR Congress Party (YSRCP)', 'BJD', 'TDP (Telugu Desam Party)',
       'YSRCP', 'JDS (Janata Dal Secular)', 'YSR Congress Party',
       'Conservative Party', 'AIMIM'], dtype=object)

In [ ]:
df['Target Party'] = df['Target Party'].replace('YSR Congress Party (YSRCP)', 'YSRCP')
df['Target Party'] = df['Target Party'].replace('YSR Congress Party', 'YSRCP')
df['Target Party'] = df['Target Party'].replace('JDS (Janata Dal Secular)', 'JDS')

In [ ]:
df['Target Party'].unique()

array(['BJP', 'TMC', nan, 'INC', 'BJP and INC', 'BJD (Biju Janata Dal)',
       'RJD', 'BRS', 'AAP and INC',
       'INC(Indian National Congress) and AAP(Aam Aadmi Party)',
       'JMM (Jharkhand Mukti Morcha)', 'AAP', 'YSRCP', 'BJD',
       'TDP (Telugu Desam Party)', 'JDS', 'Conservative Party', 'AIMIM'],
      dtype=object)

In [ ]:
df = df[df['Target Party'] != 'Conservative Party']
df['Target Party'].unique()

array(['BJP', 'TMC', nan, 'INC', 'BJP and INC', 'BJD (Biju Janata Dal)',
       'RJD', 'BRS', 'AAP and INC',
       'INC(Indian National Congress) and AAP(Aam Aadmi Party)',
       'JMM (Jharkhand Mukti Morcha)', 'AAP', 'YSRCP', 'BJD',
       'TDP (Telugu Desam Party)', 'JDS', 'AIMIM'], dtype=object)

In [ ]:
df['Target Party'] = df['Target Party'].replace('JMM (Jharkhand Mukti Morcha)', 'JMM')
df['Target Party'] = df['Target Party'].replace('TDP (Telugu Desam Party)', 'TDP')
df['Target Party'] = df['Target Party'].replace('BJD (Biju Janata Dal)', 'BJD')

In [ ]:
df['Target Party'].unique()

array(['BJP', 'TMC', nan, 'INC', 'BJP and INC', 'BJD', 'RJD', 'BRS',
       'AAP and INC', 'JMM', 'AAP', 'YSRCP', 'TDP', 'JDS', 'AIMIM'],
      dtype=object)

In [ ]:
# Splitting the 'Target Party' column and creating new rows
df['Target Party'] = df['Target Party'].str.split(' and ')
df = df.explode('Target Party')
df['Target Party'].unique()

array(['BJP', 'TMC', nan, 'INC', 'BJD', 'RJD', 'BRS', 'AAP', 'JMM',
       'YSRCP', 'TDP', 'JDS', 'AIMIM'], dtype=object)

In [ ]:
df['Target Party'].value_counts()

Target Party
BJP      247
INC       97
AAP       28
TMC        6
YSRCP      6
BJD        3
RJD        2
BRS        2
JMM        1
TDP        1
JDS        1
AIMIM      1
Name: count, dtype: int64

**Associating Alliances**

In [ ]:
df['Alliance'] = ''
df.columns

Index(['url', 'title', 'publish_date', 'authors', 'length', 'likes',
       'comments', 'views', 'description', 'political', 'non political',
       'topic', 'cleaned_description', 'text', 'cluster', 'score', 'video_id',
       'captions', 'Caption Summary', 'Orientation', 'Explanation',
       'Target Party', 'Target Person', 'Sentiment', 'Alliance'],
      dtype='object')

In [ ]:
df['Target Party'].unique()

array(['BJP', 'TMC', nan, 'INC', 'BJD', 'RJD', 'BRS', 'AAP', 'JMM',
       'YSRCP', 'TDP', 'JDS', 'AIMIM'], dtype=object)

In [ ]:
df.loc[df['Target Party'] == 'BJP', 'Alliance'] = 'NDA'
df.loc[df['Target Party'] == 'TMC', 'Alliance'] = 'INDIA'
df.loc[df['Target Party'] == 'INC', 'Alliance'] = 'INDIA'
df.loc[df['Target Party'] == 'BJD', 'Alliance'] = 'Others'
df.loc[df['Target Party'] == 'RJD', 'Alliance'] = 'INDIA'
df.loc[df['Target Party'] == 'BRS', 'Alliance'] = 'Others'
df.loc[df['Target Party'] == 'AAP', 'Alliance'] = 'INDIA'
df.loc[df['Target Party'] == 'JMM', 'Alliance'] = 'INDIA'
df.loc[df['Target Party'] == 'YSRCP', 'Alliance'] = 'Others'
df.loc[df['Target Party'] == 'TDP', 'Alliance'] = 'Others'
df.loc[df['Target Party'] == 'JDS', 'Alliance'] = 'NDA'
df.loc[df['Target Party'] == 'AIMIM', 'Alliance'] = 'Others'

In [ ]:
df['Target Party'].isna().sum()

223

In [ ]:
df['Alliance'].unique()

array(['NDA', 'INDIA', '', 'Others'], dtype=object)

In [ ]:
df['Alliance'] = df['Alliance'].replace('', None)

In [ ]:
df['Alliance'].isna().sum()

223

In [ ]:
df.to_csv('/content/en_top3_insights_NDTV.csv', index=False, quoting=1)

## **Republic World**

In [ ]:
import pandas as pd

In [ ]:
df_r = pd.read_csv('/content/en_top3_insights_Republic_World.csv')
df_r.head(5)

,url,title,publish_date,authors,length,likes,comments,views,description,political,...,cluster,score,video_id,captions,Caption Summary,Orientation,Explanation,Target Party,Target Person,Sentiment
0,https://www.youtube.com/watch?v=MgH1_b_Ixs0,Himachal Pradesh Exit Polls Result: BJP Projec...,01-06-2024,Republic World,274,0,98,32878,Himachal Pradesh Exit Polls Result: BJP Projec...,0.906262,...,0,9863.4,MgH1_b_Ixs0,पी मार्क नंबर इज शोइंग दैट अ आउट ऑफ द टोटल नंब...,The video discusses the electoral prospects of...,Supports,The video discusses the positive electoral pro...,BJP(Bharatiya Janta Party),"Kangana Ranaut, Jairam Thakur",Positive
1,https://www.youtube.com/watch?v=8FswwVN9LOg,Exit Poll Results: Massive Muslim Vote Goes To...,01-06-2024,Republic World,212,0,33,35404,"Republic TV's Matrize, P-Markq Exit Polls - th...",0.935412,...,0,10621.2,8FswwVN9LOg,the second point I want to add here is that an...,The discussion highlights a significant shift ...,Opposes,The video discusses the exit poll results indi...,BJP(Bharatiya Janta Party),Narendra Modi,Negative
2,https://www.youtube.com/watch?v=lRY851NkVzM,Exit Poll Results: Matrize Poll Predicts 360+ ...,01-06-2024,Republic World,216,0,35,47988,"Republic TV's Matrize, P-Markq Exit Polls - th...",0.942873,...,0,14396.4,lRY851NkVzM,now the matrise national projection exit poll ...,The Matrise national exit poll projects a stro...,Supports,The video discusses exit poll results that pre...,BJP(Bharatiya Janta Party),Narendra Modi,Positive
3,https://www.youtube.com/watch?v=dX1CnAem9C0,Karnataka Exit Poll Results: NDA Clear Favouri...,01-06-2024,Republic World,492,0,88,88860,Karnataka Exit Poll Results: NDA Clear Favouri...,0.871102,...,1,26658.0,dX1CnAem9C0,yes um this is much in line with what the BJP ...,The discussion revolves around the political l...,Supports,The video discusses the BJP's strong performan...,BJP(Bharatiya Janta Party),Narendra Modi,Positive
4,https://www.youtube.com/watch?v=P0CUFGUJNsQ,"PM Modi To Return With Bigger Mandate, Exit Po...",01-06-2024,Republic World,2741,0,657,201363,Republic-Matrize and Republic-P-Marq came up w...,0.855925,...,1,60408.9,P0CUFGUJNsQ,गुड इवनिंग एंड वेलकम लेडीज एंड जेंटलमेन इट्स ब...,The video discusses the results of exit polls ...,Supports,The video discusses the favorable exit poll re...,BJP(Bharatiya Janta Party),Narendra Modi,Positive

In [ ]:
df_r.columns

Index(['url', 'title', 'publish_date', 'authors', 'length', 'likes',
       'comments', 'views', 'description', 'political', 'non political',
       'text', 'topic', 'cleaned_description', 'cluster', 'score', 'video_id',
       'captions', 'Caption Summary', 'Orientation', 'Explanation',
       'Target Party', 'Target Person', 'Sentiment'],
      dtype='object')

In [ ]:
df_r.isna().sum()

url                      0
title                    0
publish_date             0
authors                  0
length                   0
likes                    0
comments                 0
views                    0
description              0
political                0
non political            0
text                     0
topic                    0
cleaned_description      0
cluster                  0
score                    0
video_id                 0
captions               104
Caption Summary          0
Orientation            160
Explanation              0
Target Party           181
Target Person          165
Sentiment                4
dtype: int64

In [ ]:
df_r['Target Party'].unique()

array(['BJP(Bharatiya Janta Party)', 'TMC(Trinamool Congress)',
       'INC(Indian National Congress)', nan, 'JD(S)',
       'AAP(Aam Aadmi Party)', 'AAP', 'NCP (Nationalist Congress Party)',
       'TMC (Trinamool Congress)', 'Shiv Sena', 'AIMIM',
       'Left party (not explicitly listed but implied as the ruling party in Kerala)',
       'BJP', 'Samajwadi Party', 'AAP and INC', 'YSR Congress Party',
       'RJD (Rashtriya Janata Dal)',
       'INC(Indian National Congress) and AAP(Aam Aadmi Party)'],
      dtype=object)

In [ ]:
df_r['Target Party'] = df_r['Target Party'].replace('BJP(Bharatiya Janta Party)', 'BJP')
df_r['Target Party'] = df_r['Target Party'].replace('TMC(Trinamool Congress)', 'TMC')
df_r['Target Party'] = df_r['Target Party'].replace('INC(Indian National Congress)', 'INC')
df_r['Target Party'] = df_r['Target Party'].replace('JD(S)', 'JDS')
df_r['Target Party'] = df_r['Target Party'].replace('AAP(Aam Aadmi Party)', 'AAP')
df_r['Target Party'] = df_r['Target Party'].replace('NCP (Nationalist Congress Party)', 'INC')
df_r['Target Party'] = df_r['Target Party'].replace('TMC (Trinamool Congress)', 'TMC')
df_r['Target Party'] = df_r['Target Party'].replace('Left party (not explicitly listed but implied as the ruling party in Kerala)', 'LDF')
df_r['Target Party'] = df_r['Target Party'].replace('YSR Congress Party', 'YSRCP')
df_r['Target Party'] = df_r['Target Party'].replace('RJD (Rashtriya Janata Dal)', 'RJD')

In [ ]:
df_r['Target Party'].unique()

array(['BJP', 'TMC', 'INC', nan, 'JDS', 'AAP', 'Shiv Sena', 'AIMIM',
       'LDF', 'Samajwadi Party', 'AAP and INC', 'YSRCP', 'RJD',
       'INC(Indian National Congress) and AAP(Aam Aadmi Party)'],
      dtype=object)

In [ ]:
df_r['Target Party'] = df_r['Target Party'].replace('INC(Indian National Congress) and AAP(Aam Aadmi Party)', 'AAP and INC')
df_r['Target Party'].unique()

array(['BJP', 'TMC', 'INC', nan, 'JDS', 'AAP', 'Shiv Sena', 'AIMIM',
       'LDF', 'Samajwadi Party', 'AAP and INC', 'YSRCP', 'RJD'],
      dtype=object)

In [ ]:
# Splitting the 'Target Party' column and creating new rows
df_r['Target Party'] = df_r['Target Party'].str.split(' and ')
df_r = df_r.explode('Target Party')
df_r['Target Party'].unique()

array(['BJP', 'TMC', 'INC', nan, 'JDS', 'AAP', 'Shiv Sena', 'AIMIM',
       'LDF', 'Samajwadi Party', 'YSRCP', 'RJD'], dtype=object)

In [ ]:
df['Target Party'].value_counts()

Target Party
BJP      247
INC       97
AAP       28
TMC        6
YSRCP      6
BJD        3
RJD        2
BRS        2
JMM        1
TDP        1
JDS        1
AIMIM      1
Name: count, dtype: int64

**Associating Alliances**

In [ ]:
df_r['Alliance'] = ''
df_r.columns

Index(['url', 'title', 'publish_date', 'authors', 'length', 'likes',
       'comments', 'views', 'description', 'political', 'non political',
       'text', 'topic', 'cleaned_description', 'cluster', 'score', 'video_id',
       'captions', 'Caption Summary', 'Orientation', 'Explanation',
       'Target Party', 'Target Person', 'Sentiment', 'Alliance'],
      dtype='object')

In [ ]:
df_r['Target Party'].unique()

array(['BJP', 'TMC', 'INC', nan, 'JDS', 'AAP', 'Shiv Sena', 'AIMIM',
       'LDF', 'Samajwadi Party', 'YSRCP', 'RJD'], dtype=object)

In [ ]:
df_r.loc[df_r['Target Party'] == 'BJP', 'Alliance'] = 'NDA'
df_r.loc[df_r['Target Party'] == 'TMC', 'Alliance'] = 'INDIA'
df_r.loc[df_r['Target Party'] == 'INC', 'Alliance'] = 'INDIA'
df_r.loc[df_r['Target Party'] == 'JDS', 'Alliance'] = 'NDA'
df_r.loc[df_r['Target Party'] == 'AAP', 'Alliance'] = 'INDIA'
df_r.loc[df_r['Target Party'] == 'Shiv Sena', 'Alliance'] = 'INDIA'
df_r.loc[df_r['Target Party'] == 'AIMIM', 'Alliance'] = 'Others'
df_r.loc[df_r['Target Party'] == 'LDF', 'Alliance'] = 'Others'
df_r.loc[df_r['Target Party'] == 'Samajwadi Party', 'Alliance'] = 'INDIA'
df_r.loc[df_r['Target Party'] == 'YSRCP', 'Alliance'] = 'Others'
df_r.loc[df_r['Target Party'] == 'RJD', 'Alliance'] = 'INDIA'

In [ ]:
df_r['Alliance'].unique()

array(['NDA', 'INDIA', '', 'Others'], dtype=object)

In [ ]:
df_r['Alliance'] = df_r['Alliance'].replace('', None)

In [ ]:
df_r['Alliance'].isna().sum()

181

In [ ]:
df_r['Target Party'].isna().sum()

181

In [ ]:
df_r.to_csv('/content/en_top3_insights_Republic_World.csv', index=False, quoting=1)

## **Times Now**

In [ ]:
import pandas as pd

In [ ]:
df_t = pd.read_csv('/home/isha/Projects/Youtube_Scrapping/output/insights/en_top3_insights_Times_Now.csv')
df_t.head(5)

In [ ]:
df_t.columns

In [ ]:
df_t['Target Party'].unique()

In [ ]:
df_t['Target Party'] = df_t['Target Party'].replace('BJP(Bharatiya Janta Party)', 'BJP')
df_t['Target Party'] = df_t['Target Party'].replace('INC(Indian National Congress)', 'INC')
df_t['Target Party'] = df_t['Target Party'].replace('BJD (Biju Janata Dal)', 'BJD')
df_t['Target Party'] = df_t['Target Party'].replace('AAP(Aam Aadmi Party)', 'AAP')
df_t['Target Party'] = df_t['Target Party'].replace('NCP (Nationalist Congress Party)', 'INC')
df_t['Target Party'] = df_t['Target Party'].replace('Congress', 'INC')
df_t['Target Party'] = df_t['Target Party'].replace('BRS (Bharat Rashtra Samithi)', 'BRS')
df_t['Target Party'] = df_t['Target Party'].replace('TMC(Trinamool Congress)', 'TMC')
df_t['Target Party'] = df_t['Target Party'].replace('TMC (Trinamool Congress)', 'TMC')
df_t['Target Party'] = df_t['Target Party'].replace('RJD (Rashtriya Janata Dal) - part of the INDIA Bloc', 'RJD')
df_t['Target Party'] = df_t['Target Party'].replace('RJD (part of the INDIA bloc)', 'RJD')
df_t['Target Party'] = df_t['Target Party'].replace('CPI(M)', 'CPI')
df_t['Target Party'] = df_t['Target Party'].replace('CPIM', 'CPI')
df_t['Target Party'] = df_t['Target Party'].replace('CPM (Communist Party of India (Marxist))', 'CPI')
df_t['Target Party'] = df_t['Target Party'].replace('AIMIM (All India Majlis-e-Ittehad-ul-Muslimeen)', 'AIMIM')
df_t['Target Party'] = df_t['Target Party'].replace('RJD (Rashtriya Janata Dal)', 'RJD')
df_t['Target Party'] = df_t['Target Party'].replace('JD(S)', 'JDS')
df_t['Target Party'] = df_t['Target Party'].replace('I.N.D.I.A bloc (specifically JMM)', 'JMM')
df_t['Target Party'] = df_t['Target Party'].replace('I.N.D.I.A bloc (including JMM)', 'JMM')
df_t['Target Party'] = df_t['Target Party'].replace('YSR Congress Party (YSRCP)', 'YSRCP')

In [ ]:
df['Target Party'].unique()

In [ ]:
# Splitting the 'Target Party' column and creating new rows
df['Target Party'] = df['Target Party'].str.split(' and ')
df = df.explode('Target Party')
df['Target Party'].unique()

In [ ]:
df['Target Party'] = df['Target Party'].replace('JD(S)', 'JDS')
df['Target Party'] = df['Target Party'].replace('Congress', 'INC')
df['Target Party'] = df['Target Party'].replace('INC(Indian National Congress)', 'INC')
df['Target Party'] = df['Target Party'].replace('AAP(Aam Aadmi Party)', 'AAP')
df['Target Party'] = df['Target Party'].replace('TMC(Trinamool Congress)', 'TMC')

In [ ]:
df_t['Target Party'].unique()

**Associating Alliances**

In [ ]:
df_t['Alliance'] = ''

In [ ]:
df_t.columns

In [ ]:
df_t['Target Party'].unique()

In [ ]:
df_t.loc[df_t['Target Party'] == 'BJP', 'Alliance'] = 'NDA'
df_t.loc[df_t['Target Party'] == 'INC', 'Alliance'] = 'INDIA'
df_t.loc[df_t['Target Party'] == 'AAP', 'Alliance'] = 'INDIA'
df_t.loc[df_t['Target Party'] == 'BJD', 'Alliance'] = 'Others'
df_t.loc[df_t['Target Party'] == 'BRS', 'Alliance'] = 'Others'
df_t.loc[df_t['Target Party'] == 'TMC', 'Alliance'] = 'INDIA'
df_t.loc[df_t['Target Party'] == 'RJD', 'Alliance'] = 'INDIA'
df_t.loc[df_t['Target Party'] == 'Samajwadi Party', 'Alliance'] = 'INDIA'
df_t.loc[df_t['Target Party'] == 'JDS', 'Alliance'] = 'NDA'
df_t.loc[df_t['Target Party'] == 'YSRCP', 'Alliance'] = 'Others'
df_t.loc[df_t['Target Party'] == 'CPI', 'Alliance'] = 'Others'
df_t.loc[df_t['Target Party'] == 'AIMIM', 'Alliance'] = 'Others'
df_t.loc[df_t['Target Party'] == 'DMK', 'Alliance'] = 'INDIA'
df_t.loc[df_t['Target Party'] == 'JMM', 'Alliance'] = 'INDIA'

In [ ]:
df_t['Alliance'].value_counts()

In [ ]:
df_t['Alliance'] = df_t['Alliance'].replace('', None)

In [ ]:
df_t['Alliance'].isna().sum()

In [ ]:
df_t['Target Party'].isna().sum()

In [ ]:
df_t.to_csv('/home/isha/Projects/Youtube_Scrapping/output/insights/en_top3_insights_Times_Now_.csv', index=False, quoting=1)

## **CNN News 18**

In [ ]:
import pandas as pd

In [ ]:
df_c = pd.read_csv('/content/en_CNN_News18_insights_tdc.csv')
df_c.head(5)

,url,title,publish_date,authors,length,likes,comments,views,description,cleaned_description,...,cluster,score,video_id,captions,Caption Summary,Orientation,Explanation,Target Party,Target Person,Sentiment
0,https://www.youtube.com/watch?v=sE-0wJd8w5w,Lok Sabha Election 2024 | BJP To Sweep Karnata...,2024-06-01,CNN-News18,275,207,69,69365,Lok Sabha Election 2024 | BJP To Sweep Karnata...,Lok Sabha Election 2024 | BJP To Sweep Karnata...,...,0,20954.4,sE-0wJd8w5w,look at the Karnataka numbers the big state wh...,The video discusses the projected election res...,Supports,The video presents a favorable outlook for the...,BJP(Bharatiya Janta Party),Narendra Modi,Positive
1,https://www.youtube.com/watch?v=izdhGlNjYRQ,Lok Sabha Elections 2024 Exit Poll | M.P. News...,2024-06-01,CNN-News18,175,49,9,187880,#News18ExitPoll | BJP is winning all 29 seats ...,| BJP is winning all 29 seats in Madhya Prade...,...,0,56398.3,izdhGlNjYRQ,वी हैव विद अस फॉर्मर मध्य प्रदेश चीफ मिनिस्टर ...,The video features former Madhya Pradesh Chief...,Supports,The video strongly supports the BJP by highlig...,BJP(Bharatiya Janta Party),Narendra Modi,Positive
2,https://www.youtube.com/watch?v=KvfMzXanTUg,Lok Sabha Elections 2024 | I.N.D.I.A Bloc Vict...,2024-05-30,CNN-News18,1427,317,151,78836,The battle for Uttar Pradesh enters its last l...,The battle for Uttar Pradesh enters its last l...,...,0,23872.7,KvfMzXanTUg,you're with the hard facts from the CNN news8 ...,"In a recent discussion on CNN, political figur...",Opposes,The video discusses the challenges faced by th...,BJP(Bharatiya Janta Party),Narendra Modi,Negative
3,https://www.youtube.com/watch?v=7wB7CDQ13N0,Ukraine Withdraws Troops Around Kharkiv As Rus...,2024-05-16,CNN-News18,556,83,17,7733,Ukraine Withdraws Troops Around Kharkiv As Rus...,Ukraine Withdraws Troops Around Kharkiv As Rus...,...,1,2378.0,7wB7CDQ13N0,NaN,Sure! Please provide the captions you'd like m...,NaN,The video discusses the situation in Ukraine r...,NaN,NaN,NaN
4,https://www.youtube.com/watch?v=wida9keMwGU,Russia Vs Ukraine | Life On Ukraine’s Front Li...,2024-05-29,CNN-News18,360,406,96,31358,Russia Vs Ukraine | Life On Ukraine’s Front Li...,Russia Vs Ukraine | Life On Ukraine’s Front Li...,...,1,9691.6,wida9keMwGU,this is our old position it is a bit further w...,The video discusses the ongoing war in Ukraine...,NaN,The video discusses the ongoing conflict betwe...,NaN,NaN,Neutral

In [ ]:
df_c.columns

Index(['url', 'title', 'publish_date', 'authors', 'length', 'likes',
       'comments', 'views', 'description', 'cleaned_description', 'political',
       'non political', 'topic', 'cluster', 'score', 'video_id', 'captions',
       'Caption Summary', 'Orientation', 'Explanation', 'Target Party',
       'Target Person', 'Sentiment'],
      dtype='object')

In [ ]:
df_c['Target Party'].unique()

array(['BJP(Bharatiya Janta Party)', nan, 'TMC(Trinamool Congress)',
       'INC(Indian National Congress)', 'ANC (African National Congress)',
       'AAP', 'BJP', 'NCP (Nationalist Congress Party)',
       'INC(Indian National Congress) and TMC(Trinamool Congress)',
       'JD(S)', 'JDS', 'AAP(Aam Aadmi Party)', 'Jana Sena Party',
       'Conservative Party', 'Labour Party', 'Samajwadi Party', 'YSRCP',
       'INC(Indian National Congress) and AAP(Aam Aadmi Party)',
       'TMC (Trinamool Congress)'], dtype=object)

In [ ]:
# Splitting the 'Target Party' column and creating new rows
df_c['Target Party'] = df_c['Target Party'].str.split(' and ')
df_c = df_c.explode('Target Party')
df_c['Target Party'].unique()

array(['BJP(Bharatiya Janta Party)', nan, 'TMC(Trinamool Congress)',
       'INC(Indian National Congress)', 'ANC (African National Congress)',
       'AAP', 'BJP', 'NCP (Nationalist Congress Party)', 'JD(S)', 'JDS',
       'AAP(Aam Aadmi Party)', 'Jana Sena Party', 'Conservative Party',
       'Labour Party', 'Samajwadi Party', 'YSRCP',
       'TMC (Trinamool Congress)'], dtype=object)

In [ ]:
# Removing rows with political discussions of some other country
df_c = df_c[df_c['Target Party']!='ANC (African National Congress)']
df_c = df_c[df_c['Target Party']!='Conservative Party']
df_c = df_c[df_c['Target Party']!='Labour Party']
df_c['Target Party'].unique()

array(['BJP(Bharatiya Janta Party)', nan, 'TMC(Trinamool Congress)',
       'INC(Indian National Congress)', 'AAP', 'BJP',
       'NCP (Nationalist Congress Party)', 'JD(S)', 'JDS',
       'AAP(Aam Aadmi Party)', 'Jana Sena Party', 'Samajwadi Party',
       'YSRCP', 'TMC (Trinamool Congress)'], dtype=object)

In [ ]:
df_c['Target Party'] = df_c['Target Party'].replace('BJP(Bharatiya Janta Party)', 'BJP')
df_c['Target Party'] = df_c['Target Party'].replace('TMC(Trinamool Congress)', 'TMC')
df_c['Target Party'] = df_c['Target Party'].replace('TMC (Trinamool Congress)', 'TMC')
df_c['Target Party'] = df_c['Target Party'].replace('INC(Indian National Congress)', 'INC')
df_c['Target Party'] = df_c['Target Party'].replace('NCP (Nationalist Congress Party)', 'INC')
df_c['Target Party'] = df_c['Target Party'].replace('AAP(Aam Aadmi Party)', 'AAP')
df_c['Target Party'] = df_c['Target Party'].replace('JD(S)', 'JDS')
df_c['Target Party'] = df_c['Target Party'].replace('Jana Sena Party', 'JSP')

In [ ]:
df_c['Target Party'].unique()

array(['BJP', nan, 'TMC', 'INC', 'AAP', 'JDS', 'JSP', 'Samajwadi Party',
       'YSRCP'], dtype=object)

**Associating Alliances**

In [ ]:
df_c['Alliance'] = ''

In [ ]:
df_c.columns

Index(['url', 'title', 'publish_date', 'authors', 'length', 'likes',
       'comments', 'views', 'description', 'cleaned_description', 'political',
       'non political', 'topic', 'cluster', 'score', 'video_id', 'captions',
       'Caption Summary', 'Orientation', 'Explanation', 'Target Party',
       'Target Person', 'Sentiment', 'Alliance'],
      dtype='object')

In [ ]:
df_c['Target Party'].unique()

array(['BJP', nan, 'TMC', 'INC', 'AAP', 'JDS', 'JSP', 'Samajwadi Party',
       'YSRCP'], dtype=object)

In [ ]:
df_c.loc[df_c['Target Party'] == 'BJP', 'Alliance'] = 'NDA'
df_c.loc[df_c['Target Party'] == 'INC', 'Alliance'] = 'INDIA'
df_c.loc[df_c['Target Party'] == 'AAP', 'Alliance'] = 'INDIA'
df_c.loc[df_c['Target Party'] == 'TMC', 'Alliance'] = 'INDIA'
df_c.loc[df_c['Target Party'] == 'Samajwadi Party', 'Alliance'] = 'INDIA'
df_c.loc[df_c['Target Party'] == 'JDS', 'Alliance'] = 'NDA'
df_c.loc[df_c['Target Party'] == 'YSRCP', 'Alliance'] = 'Others'
df_c.loc[df_c['Target Party'] == 'JSP', 'Alliance'] = 'NDA'

In [ ]:
df_c['Alliance'].value_counts()

Alliance
          250
NDA       197
INDIA     162
Others      1
Name: count, dtype: int64

In [ ]:
df_c['Alliance'] = df_c['Alliance'].replace('', None)

In [ ]:
df_c['Alliance'].isna().sum()

250

In [ ]:
df_c['Target Party'].isna().sum()

250

In [ ]:
df_c.to_csv('/content/en_CNN_News18_insights_tdc.csv', index=False, quoting=1)